# conjur policy load cd/kubernetes cd/kubernetes/api-app.yml

- !policy
  id: api-app
  owner: !group admins
  annotations:
    description: Kubernetes application retrieving secrets using API delivery method
    kubernetes: true
  body:
    - !host
      annotations:
        authn-k8s/namespace: api-app
        authn-k8s/service-account: api-app-account
        authn-k8s/authentication-container-name: authenticator
        kubernetes: true
