# conjur policy load cd/kubernetes cd/kubernetes/api-app.yml

- !policy
  id: api-app
  owner: !group admins
  annotations:
    description: Kubernetes application retrieving secrets using API delivery method
    kubernetes: true
  body:
    - !host

    # Grant kubernetes host identity to the consumers group for authn-k8s
    - !grant
      role: !group authn-k8s/conjur-demo/consumers
      member: !host