# conjur policy load cd/kubernetes cd/kubernetes/k8s-secrets-app.yml

- !policy
  id: k8s-secrets-app
  owner: !group admins
  annotations:
    description: Kubernetes application retrieving secrets using Kubernetes Secrets push method
    kubernetes: true
  body:
    - !host

    # Grant kubernetes host identity to the consumers group for authn-k8s
    - !grant
      role: !group /authn-k8s/conjur-demo/consumers
      member: !host