# conjur policy load cd kubernetes.yml

- !policy
  id: kubernetes
  annotations:
    description: Resources and secret definitions for Kubernetes applications.
    kubernetes: true
  body:
    # Create secret variables for secret delivery method apps
    - &variables
      - !variable db/host
      - !variable db/username
      - !variable db/password
      - !variable db/name

    # Create group for admins - cd/kubernetes/admins
    - !group
      id: admins
      annotations:
        description: Owner of kubernetes branch policies
        editable: "true"

    # Grant conjur-admins to be kubernetes/admins
    - !grant
      role: !group admins
      members:
        - !group /conjur-admins
    
    # Create group for secrets-users - cd/kubernetes/secrets-users
    - !group
      id: secrets-users
      annotations:
        description: Users of secrets defined in cd/kubernetes policy
        editable: "true"
    
    # Permit secrets-users group to read & execute secret variables
    - !permit
      role: !group secrets-users
      privileges: [ read, execute ]
      resources: *variables

    # Create group for authn-k8s consumers - cd/kubernetes/authn-k8s/conjur-demo/consumers
    - !group
      id: authn-k8s/conjur-demo/consumers
      annotations:
        description: Group containing host identities that can authenticate to authn-k8s/conjur-demo
        editable: "true"