# conjur policy load cd/kubernetes cd/kubernetes/secretless-app.yml

- !policy
  id: secretless-app
  owner: !group admins
  annotations:
    description: Kubernetes application retrieving secrets using Secretless Broker delivery method
    kubernetes: true
  body:
    - !host