# conjur policy load cd/kubernetes cd/kubernetes/summon-app.yml

- !policy
  id: summon-app
  owner: !group admins
  annotations:
    description: Kubernetes application retrieving secrets using Summon delivery method
    kubernetes: true
  body:
    - !host

    # Grant kubernetes host identity to the consumers group for authn-k8s
    - !grant
      role: !group /cd/kubernetes/authn-k8s/conjur-demo/consumers
      member: !host